AWSTemplateFormatVersion: '2010-09-09'
Description: 'decodedmusic Authentication Stack - Created by artist, for artists | AWS Account: 3969-1370-3024'

Parameters:
  Environment:
    Type: String
    Default: prod
  UserPoolId:
    Type: String
    Description: Existing Cognito User Pool ID
    Default: eu-central-1_d9JNeVdni
  UserPoolClientId:
    Type: String
    Description: Existing Cognito App Client ID
    Default: 5pb29tja8gkqm3jb43oimd5qjt
  LambdaCodeBucket:
    Type: String
    Default: decodedmusic-lambda-code
  AuthLoginS3Key:
    Type: String
    Default: authLogin.zip
  AuthSignupS3Key:
    Type: String
    Default: authSignup.zip
  SubscriptionCreateS3Key:
    Type: String
    Default: subscriptionCreate.zip

Resources:
  LambdaFunctionsModule:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: modules/lambda-functions.yml
      Parameters:
        Environment: !Ref Environment
        LambdaCodeBucket: !Ref LambdaCodeBucket
        AuthLoginS3Key: !Ref AuthLoginS3Key
        AuthSignupS3Key: !Ref AuthSignupS3Key
        SubscriptionCreateS3Key: !Ref SubscriptionCreateS3Key
        CognitoClientId: !Ref UserPoolClientId
        UsersTableName: !Sub "${Environment}-decodedmusic-users"

Outputs:
  AuthLoginFunctionArn:
    Value: !GetAtt LambdaFunctionsModule.Outputs.AuthLoginFunctionArn
    Export:
      Name: !Sub "${Environment}-AuthLoginArn"
  AuthSignupFunctionArn:
    Value: !GetAtt LambdaFunctionsModule.Outputs.AuthSignupFunctionArn
    Export:
      Name: !Sub "${Environment}-AuthSignupArn"
