AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  LambdaCodeBucket:
    Type: String
    Default: decodedmusic-lambda-code
Resources:
  ContactFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs18.x
      Role: !GetAtt ContactFunctionRole.Arn
      Code:
        S3Bucket: !Ref LambdaCodeBucket
        S3Key: prod-dashboardStreams.zip
  ContactFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: allowSES
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: ses:SendEmail
                Resource: '*'




