AWSTemplateFormatVersion: '2010-09-09'
Description: Backend stack for Decoded Music using Lambda, API Gateway and DynamoDB

Parameters:
  EnvName:
    Type: String
    Default: prod
    Description: Environment name prefix
  ExistingTableName:
    Type: String
    Default: prod-DecodedMusicItems
    Description: Existing DynamoDB table name for backend lambda

Resources:
  BackendLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: dynamodb-access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:Scan
                Resource: '*'
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'

  BackendLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${EnvName}-backendHandler"
      Runtime: nodejs18.x
      Handler: index.handler
      Role: !GetAtt BackendLambdaRole.Arn
      Environment:
        Variables:
          TABLE_NAME: !Ref ExistingTableName
      Code:
        S3Bucket: decodedmusic-lambda-code
        S3Key: backend.zip

  ApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: DecodedMusicBackendApi

  ApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt ApiGateway.RootResourceId
      PathPart: backend
      RestApiId: !Ref ApiGateway

  ApiMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: ANY
      ResourceId: !Ref ApiResource
      RestApiId: !Ref ApiGateway
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${BackendLambda.Arn}/invocations'

  LambdaPermissionApi:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref BackendLambda
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGateway}/*/*/backend'

Outputs:
  ApiUrl:
    Description: Endpoint for the DecodedMusicBackend API
    Value: !Sub 'https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod/backend'
