AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Attach catalog and dashboard lambdas to API Gateway with CORS and artistId support

Parameters:
  EnvName:
    Type: String
    Default: prod
    Description: Environment name prefix

Globals:
  Function:
    Timeout: 3
    Runtime: nodejs18.x
    MemorySize: 128

Resources:
  DecodedCatalogTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${EnvName}-DecodedCatalog-${AWS::StackName}'
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  DecodedCTATable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${EnvName}-DecodedCTA-${AWS::StackName}'
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  RevenueLogTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${EnvName}-RevenueLog-${AWS::StackName}'
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  ExpenseLogTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${EnvName}-ExpenseLog-${AWS::StackName}'
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  WeeklyArtistStatsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${EnvName}-WeeklyArtistStats-${AWS::StackName}'
      AttributeDefinitions:
        - AttributeName: artist_id
          AttributeType: S
        - AttributeName: week_start
          AttributeType: S
      KeySchema:
        - AttributeName: artist_id
          KeyType: HASH
        - AttributeName: week_start
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  StatementsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${EnvName}-Statements-${AWS::StackName}'
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  # === Auth Functions ===
  # SpotifyAuthHandler -> Role: arn:aws:iam::396913703024:role/decoded-genai-stack-BackendLambdaRole-7PvuaEMzpSHR, S3Key: spotifyAuthHandler.zip, Env: SPOTIFY_CLIENT_ID, SPOTIFY_REDIRECT_URI
  SpotifyAuthHandler:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${EnvName}-spotifyAuthHandler'
      Handler: index.handler
      Runtime: nodejs18.x
      Role: arn:aws:iam::396913703024:role/decoded-genai-stack-BackendLambdaRole-7PvuaEMzpSHR
      Code:
        S3Bucket: decodedmusic-lambda-code
        S3Key: spotifyAuthHandler.zip
      Environment:
        Variables:
          SPOTIFY_CLIENT_ID: 5866a38ab59f46b2b8ceebfa17540d32
          SPOTIFY_REDIRECT_URI: https://decodedmusic.com/dashboard
      Timeout: 10
      MemorySize: 128

  # SpotifyCallbackHandler -> Role: arn:aws:iam::396913703024:role/decoded-genai-stack-BackendLambdaRole-7PvuaEMzpSHR, S3Key: spotifyCallbackHandler.zip, Env: SPOTIFY_CLIENT_ID, SPOTIFY_CLIENT_SECRET, SPOTIFY_REDIRECT_URI
  SpotifyCallbackHandler:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${EnvName}-spotifyCallbackHandler'
      Handler: index.handler
      Runtime: nodejs18.x
      Role: arn:aws:iam::396913703024:role/decoded-genai-stack-BackendLambdaRole-7PvuaEMzpSHR
      Code:
        S3Bucket: decodedmusic-lambda-code
        S3Key: spotifyCallbackHandler.zip
      Environment:
        Variables:
          SPOTIFY_CLIENT_ID: 5866a38ab59f46b2b8ceebfa17540d32
          SPOTIFY_CLIENT_SECRET: YOUR_SPOTIFY_SECRET
          SPOTIFY_REDIRECT_URI: https://decodedmusic.com/dashboard
      Timeout: 10
      MemorySize: 128

  # === Dashboard Functions ===
  # CatalogFunction -> Role: arn:aws:iam::396913703024:role/decoded-music-resources-CatalogLambdaRole-8APIdPDKgFm8, S3Key: prod-dashboardCatalog.zip, Env: CATALOG_TABLE
  CatalogFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: prod-catalog-handler
      Handler: index.handler
      Runtime: nodejs18.x
      Role: arn:aws:iam::396913703024:role/decoded-music-resources-CatalogLambdaRole-8APIdPDKgFm8
      Code:
        S3Bucket: decodedmusic-lambda-code
        S3Key: prod-dashboardCatalog.zip
      Environment:
        Variables:
          CATALOG_TABLE: prod-Catalog
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref DecodedApi
            Path: /catalog
            Method: GET

  # DashboardStreamsFunction -> Role: arn:aws:iam::396913703024:role/decoded-genai-stack-backend-DashboardLambdaRole-YkDbqxxNlaMR, S3Key: prod-dashboardStreams.zip, Env: DYNAMO_TABLE_STREAMS
  DashboardStreamsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: prod-dashboardStreams
      Handler: index.handler
      Runtime: nodejs18.x
      Role: arn:aws:iam::396913703024:role/decoded-genai-stack-backend-DashboardLambdaRole-YkDbqxxNlaMR
      Code:
        S3Bucket: decodedmusic-lambda-code
        S3Key: prod-dashboardStreams.zip
      Environment:
        Variables:
          DYNAMO_TABLE_STREAMS: prod-DecodedStreams
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref DecodedApi
            Path: /dashboard/streams
            Method: GET

  # DashboardEarningsFunction -> S3Key: prod-dashboardEarnings.zip, Env: DYNAMO_TABLE_EARNINGS
  DashboardEarningsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: prod-dashboardEarnings
      Handler: index.handler
      Runtime: nodejs18.x
      Code:
        S3Bucket: decodedmusic-lambda-code
        S3Key: prod-dashboardEarnings.zip
      Environment:
        Variables:
          DYNAMO_TABLE_EARNINGS: prod-DecodedEarnings
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref DecodedApi
            Path: /dashboard/earnings
            Method: GET

  # DashboardCatalogFunction -> S3Key: prod-dashboardCatalog.zip, Env: DYNAMO_TABLE_CATALOG
  DashboardCatalogFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: prod-dashboardCatalog
      Handler: index.handler
      Runtime: nodejs18.x
      Code:
        S3Bucket: decodedmusic-lambda-code
        S3Key: prod-dashboardCatalog.zip
      Environment:
        Variables:
          DYNAMO_TABLE_CATALOG: prod-DecodedCatalog
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref DecodedApi
            Path: /dashboard/catalog
            Method: GET

  # DashboardAnalyticsFunction -> S3Key: prod-dashboardAnalytics.zip, Env: DYNAMO_TABLE_ANALYTICS
  DashboardAnalyticsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: prod-dashboardAnalytics
      Handler: index.handler
      Runtime: nodejs18.x
      Code:
        S3Bucket: decodedmusic-lambda-code
        S3Key: prod-dashboardAnalytics.zip
      Environment:
        Variables:
          DYNAMO_TABLE_ANALYTICS: prod-WeeklyArtistStats
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref DecodedApi
            Path: /dashboard/analytics
            Method: GET

  # DashboardStatementsFunction -> S3Key: prod-dashboardStatements.zip, Env: DYNAMO_TABLE_STATEMENTS
  DashboardStatementsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: prod-dashboardStatements
      Handler: index.handler
      Runtime: nodejs18.x
      Code:
        S3Bucket: decodedmusic-lambda-code
        S3Key: prod-dashboardStatements.zip
      Environment:
        Variables:
          DYNAMO_TABLE_STATEMENTS: prod-Statements
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref DecodedApi
            Path: /dashboard/statements
            Method: GET

  # DashboardCampaignsFunction -> S3Key: prod-dashboardCampaigns.zip, Env: SPEND_TABLE
  DashboardCampaignsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: prod-dashboardCampaigns
      Handler: index.handler
      Runtime: nodejs18.x
      Code:
        S3Bucket: decodedmusic-lambda-code
        S3Key: prod-dashboardCampaigns.zip
      Environment:
        Variables:
          SPEND_TABLE: prod-MarketingSpend
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref DecodedApi
            Path: /dashboard/campaigns
            Method: GET

  # DashboardSpotifyFunction -> S3Key: prod-dashboardSpotify.zip, Env: SPOTIFY_TABLE
  DashboardSpotifyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: prod-dashboardSpotify
      Handler: index.handler
      Runtime: nodejs18.x
      Code:
        S3Bucket: decodedmusic-lambda-code
        S3Key: prod-dashboardSpotify.zip
      Environment:
        Variables:
          SPOTIFY_TABLE: prod-SpotifyArtistData
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref DecodedApi
            Path: /dashboard/spotify
            Method: GET

  # DashboardAccountingFunction -> S3Key: prod-dashboardAccounting.zip, Env: REVENUE_TABLE, EXPENSE_TABLE
  DashboardAccountingFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: prod-dashboardAccounting
      Handler: index.handler
      Runtime: nodejs18.x
      Code:
        S3Bucket: decodedmusic-lambda-code
        S3Key: prod-dashboardAccounting.zip
      Environment:
        Variables:
          REVENUE_TABLE: prod-RevenueLog
          EXPENSE_TABLE: prod-ExpenseLog
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref DecodedApi
            Path: /dashboard/accounting
            Method: GET

  # DashboardTeamFunction -> S3Key: prod-dashboardTeam.zip, Env: TEAM_JSON
  DashboardTeamFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: prod-dashboardTeam
      Handler: index.handler
      Runtime: nodejs18.x
      Code:
        S3Bucket: decodedmusic-lambda-code
        S3Key: prod-dashboardTeam.zip
      Environment:
        Variables:
          TEAM_JSON: '[]'
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref DecodedApi
            Path: /dashboard/team
            Method: GET

# === Marketing Functions ===
# See cloudformation/marketing-hub.yml for marketing Lambdas

# === Subscription Functions ===
# See cloudformation/subscription-stack.yml for subscription Lambdas

  DecodedApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: decodedmusic-api
      StageName: !Ref EnvName
      Cors:
        AllowMethods: "GET,POST,OPTIONS"
        AllowHeaders: "Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token"
        AllowOrigin: "https://decodedmusic.com"

Outputs:
  CatalogApi:
    Description: "Catalog endpoint"
    Value: !Sub "https://${DecodedApi}.execute-api.${AWS::Region}.amazonaws.com/${EnvName}/dashboard/catalog"

  DashboardApi:
    Description: "Dashboard streams endpoint"
    Value: !Sub "https://${DecodedApi}.execute-api.${AWS::Region}.amazonaws.com/${EnvName}/dashboard/streams"
