service: decoded-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1

functions:
  apiService:
    handler: backend/handlers/apiService/handler.handler
    events:
      - http:
          path: api
          method: get
  analytics:
    handler: backend/handlers/analytics-lambda/handler.handler
  auth:
    handler: backend/handlers/auth-lambda/handler.handler
