AWSTemplateFormatVersion: '2010-09-09'
Description: 'decodedmusic Auth & Subscription Lambda Functions (nested)'

Parameters:
  Environment:
    Type: String
    Default: prod
  LambdaCodeBucket:
    Type: String
    Default: decodedmusic-lambda-code
  AuthLoginS3Key:
    Type: String
    Default: authLogin.zip
  AuthSignupS3Key:
    Type: String
    Default: authSignup.zip
  SubscriptionCreateS3Key:
    Type: String
    Default: subscriptionCreate.zip

Resources:
  LambdaFunctionsModule:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../modules/lambda-functions.yml
      Parameters:
        Environment: !Ref Environment
        LambdaCodeBucket: !Ref LambdaCodeBucket
        AuthLoginS3Key: !Ref AuthLoginS3Key
        AuthSignupS3Key: !Ref AuthSignupS3Key
        SubscriptionCreateS3Key: !Ref SubscriptionCreateS3Key

Outputs:
  AuthLoginFunctionArn:
    Value: !GetAtt LambdaFunctionsModule.Outputs.AuthLoginFunctionArn
  AuthSignupFunctionArn:
    Value: !GetAtt LambdaFunctionsModule.Outputs.AuthSignupFunctionArn
  SubscriptionCreateFunctionArn:
    Value: !GetAtt LambdaFunctionsModule.Outputs.SubscriptionCreateFunctionArn
  LambdaRoleArn:
    Value: !GetAtt LambdaFunctionsModule.Outputs.LambdaRoleArn
