Name: onPushToMainDeploymentWorkflow
SchemaVersion: "1.0"
Triggers:
  - Type: PUSH
    Branches:
      - main
Actions:
  BackendTest:
    Identifier: aws/managed-test@v1
    Inputs:
      Sources:
        - WorkflowSource
    Outputs:
      AutoDiscoverReports:
        IncludePaths:
          - "**/*"
        ExcludePaths:
          - "*/.aws/workflows/*"
        ReportNamePrefix: AutoDiscovered
        Enabled: true
    Configuration:
      Steps:
        - Run: npm install
        - Run: npm test
        - Run: npm run coverage
  BackendCDKBootstrapAction:
    Identifier: aws/cdk-bootstrap@v1
    Compute:
      Type: Lambda
    Inputs:
      Sources:
        - WorkflowSource
    Configuration:
      Region: eu-central-1
    Environment:
      Name: default_environment
      Connections:
        - Name: "396913703024"
          Role: CodeCatalystWorkflowDevelopmentRole-DECODEDMUSIC
  BackendCDKDeploy:
    Identifier: aws/cdk-deploy@v1
    Compute:
      Type: EC2
    Inputs:
      Sources:
        - WorkflowSource
    DependsOn:
      - BackendCDKBootstrapAction
      - BackendTest
    Configuration:
      StackName: decoded-genai-stack
      Region: eu-central-1
      Context: '{"stack_name": "decoded-genai-stack"}'
    Environment:
      Name: default_environment
      Connections:
        - Name: "396913703024"
          Role: CodeCatalystWorkflowDevelopmentRole-DECODEDMUSIC
